// Add this at the top of your file, after imports
class CountryCode {
  final String name;
  final String code;
  final String dialCode;
  final String flag;

  CountryCode({
    required this.name,
    required this.code,
    required this.dialCode,
    required this.flag,
  });
}

// Expanded list to include all countries in the Global South (Africa, Latin America & Caribbean, developing Asia, and Pacific islands),
// ensuring comprehensive coverage of Africa as requested. This includes all 54 African countries and key representatives from other regions.
final List<CountryCode> countryCodes = [
  // Africa (all 54 countries)
  CountryCode(name: 'Algeria', code: 'DZ', dialCode: '+213', flag: '🇩🇿'),
  CountryCode(name: 'Angola', code: 'AO', dialCode: '+244', flag: '🇦🇴'),
  CountryCode(name: 'Benin', code: 'BJ', dialCode: '+229', flag: '🇧🇯'),
  CountryCode(name: 'Botswana', code: 'BW', dialCode: '+267', flag: '🇧🇼'),
  CountryCode(name: 'Burkina Faso', code: 'BF', dialCode: '+226', flag: '🇧🇫'),
  CountryCode(name: 'Burundi', code: 'BI', dialCode: '+257', flag: '🇧🇮'),
  CountryCode(name: 'Cameroon', code: 'CM', dialCode: '+237', flag: '🇨🇲'),
  CountryCode(name: 'Cape Verde', code: 'CV', dialCode: '+238', flag: '🇨🇻'),
  CountryCode(name: 'Central African Republic', code: 'CF', dialCode: '+236', flag: '🇨🇫'),
  CountryCode(name: 'Chad', code: 'TD', dialCode: '+235', flag: '🇹🇩'),
  CountryCode(name: 'Comoros', code: 'KM', dialCode: '+269', flag: '🇰🇲'),
  CountryCode(name: 'Congo', code: 'CG', dialCode: '+242', flag: '🇨🇬'),
  CountryCode(name: 'Democratic Republic of the Congo', code: 'CD', dialCode: '+243', flag: '🇨🇩'),
  CountryCode(name: 'Djibouti', code: 'DJ', dialCode: '+253', flag: '🇩🇯'),
  CountryCode(name: 'Egypt', code: 'EG', dialCode: '+20', flag: '🇪🇬'),
  CountryCode(name: 'Equatorial Guinea', code: 'GQ', dialCode: '+240', flag: '🇬🇶'),
  CountryCode(name: 'Eritrea', code: 'ER', dialCode: '+291', flag: '🇪🇷'),
  CountryCode(name: 'Eswatini', code: 'SZ', dialCode: '+268', flag: '🇸🇿'),
  CountryCode(name: 'Ethiopia', code: 'ET', dialCode: '+251', flag: '🇪🇹'),
  CountryCode(name: 'Gabon', code: 'GA', dialCode: '+241', flag: '🇬🇦'),
  CountryCode(name: 'Gambia', code: 'GM', dialCode: '+220', flag: '🇬🇲'),
  CountryCode(name: 'Ghana', code: 'GH', dialCode: '+233', flag: '🇬🇭'),
  CountryCode(name: 'Guinea', code: 'GN', dialCode: '+224', flag: '🇬🇳'),
  CountryCode(name: 'Guinea-Bissau', code: 'GW', dialCode: '+245', flag: '🇬🇼'),
  CountryCode(name: 'Ivory Coast', code: 'CI', dialCode: '+225', flag: '🇨🇮'),
  CountryCode(name: 'Kenya', code: 'KE', dialCode: '+254', flag: '🇰🇪'),
  CountryCode(name: 'Lesotho', code: 'LS', dialCode: '+266', flag: '🇱🇸'),
  CountryCode(name: 'Liberia', code: 'LR', dialCode: '+231', flag: '🇱🇷'),
  CountryCode(name: 'Libya', code: 'LY', dialCode: '+218', flag: '🇱🇾'),
  CountryCode(name: 'Madagascar', code: 'MG', dialCode: '+261', flag: '🇲🇬'),
  CountryCode(name: 'Malawi', code: 'MW', dialCode: '+265', flag: '🇲🇼'),
  CountryCode(name: 'Mali', code: 'ML', dialCode: '+223', flag: '🇲🇱'),
  CountryCode(name: 'Mauritania', code: 'MR', dialCode: '+222', flag: '🇲🇷'),
  CountryCode(name: 'Mauritius', code: 'MU', dialCode: '+230', flag: '🇲🇺'),
  CountryCode(name: 'Morocco', code: 'MA', dialCode: '+212', flag: '🇲🇦'),
  CountryCode(name: 'Mozambique', code: 'MZ', dialCode: '+258', flag: '🇲🇿'),
  CountryCode(name: 'Namibia', code: 'NA', dialCode: '+264', flag: '🇳🇦'),
  CountryCode(name: 'Niger', code: 'NE', dialCode: '+227', flag: '🇳🇪'),
  CountryCode(name: 'Nigeria', code: 'NG', dialCode: '+234', flag: '🇳🇬'),
  CountryCode(name: 'Rwanda', code: 'RW', dialCode: '+250', flag: '🇷🇼'),
  CountryCode(name: 'Sao Tome and Principe', code: 'ST', dialCode: '+239', flag: '🇸🇹'),
  CountryCode(name: 'Senegal', code: 'SN', dialCode: '+221', flag: '🇸🇳'),
  CountryCode(name: 'Seychelles', code: 'SC', dialCode: '+248', flag: '🇸🇨'),
  CountryCode(name: 'Sierra Leone', code: 'SL', dialCode: '+232', flag: '🇸🇱'),
  CountryCode(name: 'Somalia', code: 'SO', dialCode: '+252', flag: '🇸🇴'),
  CountryCode(name: 'South Africa', code: 'ZA', dialCode: '+27', flag: '🇿🇦'),
  CountryCode(name: 'South Sudan', code: 'SS', dialCode: '+211', flag: '🇸🇸'),
  CountryCode(name: 'Sudan', code: 'SD', dialCode: '+249', flag: '🇸🇩'),
  CountryCode(name: 'Tanzania', code: 'TZ', dialCode: '+255', flag: '🇹🇿'),
  CountryCode(name: 'Togo', code: 'TG', dialCode: '+228', flag: '🇹🇬'),
  CountryCode(name: 'Tunisia', code: 'TN', dialCode: '+216', flag: '🇹🇳'),
  CountryCode(name: 'Uganda', code: 'UG', dialCode: '+256', flag: '🇺🇬'),
  CountryCode(name: 'Zambia', code: 'ZM', dialCode: '+260', flag: '🇿🇲'),
  CountryCode(name: 'Zimbabwe', code: 'ZW', dialCode: '+263', flag: '🇿🇼'),

  // Latin America and Caribbean (selected major countries)
  CountryCode(name: 'Argentina', code: 'AR', dialCode: '+54', flag: '🇦🇷'),
  CountryCode(name: 'Bolivia', code: 'BO', dialCode: '+591', flag: '🇧🇴'),
  CountryCode(name: 'Brazil', code: 'BR', dialCode: '+55', flag: '🇧🇷'),
  CountryCode(name: 'Chile', code: 'CL', dialCode: '+56', flag: '🇨🇱'),
  CountryCode(name: 'Colombia', code: 'CO', dialCode: '+57', flag: '🇨🇴'),
  CountryCode(name: 'Costa Rica', code: 'CR', dialCode: '+506', flag: '🇨🇷'),
  CountryCode(name: 'Cuba', code: 'CU', dialCode: '+53', flag: '🇨🇺'),
  CountryCode(name: 'Dominican Republic', code: 'DO', dialCode: '+1-809', flag: '🇩🇴'),
  CountryCode(name: 'Ecuador', code: 'EC', dialCode: '+593', flag: '🇪🇨'),
  CountryCode(name: 'El Salvador', code: 'SV', dialCode: '+503', flag: '🇸🇻'),
  CountryCode(name: 'Guatemala', code: 'GT', dialCode: '+502', flag: '🇬🇹'),
  CountryCode(name: 'Haiti', code: 'HT', dialCode: '+509', flag: '🇭🇹'),
  CountryCode(name: 'Honduras', code: 'HN', dialCode: '+504', flag: '🇭🇳'),
  CountryCode(name: 'Mexico', code: 'MX', dialCode: '+52', flag: '🇲🇽'),
  CountryCode(name: 'Nicaragua', code: 'NI', dialCode: '+505', flag: '🇳🇮'),
  CountryCode(name: 'Panama', code: 'PA', dialCode: '+507', flag: '🇵🇦'),
  CountryCode(name: 'Paraguay', code: 'PY', dialCode: '+595', flag: '🇵🇾'),
  CountryCode(name: 'Peru', code: 'PE', dialCode: '+51', flag: '🇵🇪'),
  CountryCode(name: 'Uruguay', code: 'UY', dialCode: '+598', flag: '🇺🇾'),
  CountryCode(name: 'Venezuela', code: 'VE', dialCode: '+58', flag: '🇻🇪'),
  CountryCode(name: 'Antigua and Barbuda', code: 'AG', dialCode: '+1-268', flag: '🇦🇬'),
  CountryCode(name: 'Bahamas', code: 'BS', dialCode: '+1-242', flag: '🇧🇸'),
  CountryCode(name: 'Barbados', code: 'BB', dialCode: '+1-246', flag: '🇧🇧'),
  CountryCode(name: 'Belize', code: 'BZ', dialCode: '+501', flag: '🇧🇿'),
  CountryCode(name: 'Dominica', code: 'DM', dialCode: '+1-767', flag: '🇩🇲'),
  CountryCode(name: 'Grenada', code: 'GD', dialCode: '+1-473', flag: '🇬🇩'),
  CountryCode(name: 'Guyana', code: 'GY', dialCode: '+592', flag: '🇬🇾'),
  CountryCode(name: 'Jamaica', code: 'JM', dialCode: '+1-876', flag: '🇯🇲'),
  CountryCode(name: 'Saint Kitts and Nevis', code: 'KN', dialCode: '+1-869', flag: '🇰🇳'),
  CountryCode(name: 'Saint Lucia', code: 'LC', dialCode: '+1-758', flag: '🇱🇨'),
  CountryCode(name: 'Saint Vincent and the Grenadines', code: 'VC', dialCode: '+1-784', flag: '🇻🇨'),
  CountryCode(name: 'Suriname', code: 'SR', dialCode: '+597', flag: '🇸🇷'),
  CountryCode(name: 'Trinidad and Tobago', code: 'TT', dialCode: '+1-868', flag: '🇹🇹'),

  // Asia (developing countries in Global South, East)
  CountryCode(name: 'Afghanistan', code: 'AF', dialCode: '+93', flag: '🇦🇫'),
  CountryCode(name: 'Bangladesh', code: 'BD', dialCode: '+880', flag: '🇧🇩'),
  CountryCode(name: 'Bhutan', code: 'BT', dialCode: '+975', flag: '🇧🇹'),
  CountryCode(name: 'Cambodia', code: 'KH', dialCode: '+855', flag: '🇰🇭'),
  CountryCode(name: 'China', code: 'CN', dialCode: '+86', flag: '🇨🇳'),
  CountryCode(name: 'India', code: 'IN', dialCode: '+91', flag: '🇮🇳'),
  CountryCode(name: 'Indonesia', code: 'ID', dialCode: '+62', flag: '🇮🇩'),
  CountryCode(name: 'Iran', code: 'IR', dialCode: '+98', flag: '🇮🇷'),
  CountryCode(name: 'Iraq', code: 'IQ', dialCode: '+964', flag: '🇮🇶'),
  CountryCode(name: 'Jordan', code: 'JO', dialCode: '+962', flag: '🇯🇴'),
  CountryCode(name: 'Kazakhstan', code: 'KZ', dialCode: '+7', flag: '🇰🇿'),
  CountryCode(name: 'Kyrgyzstan', code: 'KG', dialCode: '+996', flag: '🇰🇬'),
  CountryCode(name: 'Laos', code: 'LA', dialCode: '+856', flag: '🇱🇦'),
  CountryCode(name: 'Lebanon', code: 'LB', dialCode: '+961', flag: '🇱🇧'),
  CountryCode(name: 'Malaysia', code: 'MY', dialCode: '+60', flag: '🇲🇾'),
  CountryCode(name: 'Maldives', code: 'MV', dialCode: '+960', flag: '🇲🇻'),
  CountryCode(name: 'Mongolia', code: 'MN', dialCode: '+976', flag: '🇲🇳'),
  CountryCode(name: 'Myanmar', code: 'MM', dialCode: '+95', flag: '🇲🇲'),
  CountryCode(name: 'Nepal', code: 'NP', dialCode: '+977', flag: '🇳🇵'),
  CountryCode(name: 'Oman', code: 'OM', dialCode: '+968', flag: '🇴🇲'),
  CountryCode(name: 'Pakistan', code: 'PK', dialCode: '+92', flag: '🇵🇰'),
  CountryCode(name: 'Philippines', code: 'PH', dialCode: '+63', flag: '🇵🇭'),
  CountryCode(name: 'Saudi Arabia', code: 'SA', dialCode: '+966', flag: '🇸🇦'),
  CountryCode(name: 'Sri Lanka', code: 'LK', dialCode: '+94', flag: '🇱🇰'),
  CountryCode(name: 'Syria', code: 'SY', dialCode: '+963', flag: '🇸🇾'),
  CountryCode(name: 'Tajikistan', code: 'TJ', dialCode: '+992', flag: '🇹🇯'),
  CountryCode(name: 'Thailand', code: 'TH', dialCode: '+66', flag: '🇹🇭'),
  CountryCode(name: 'Timor-Leste', code: 'TL', dialCode: '+670', flag: '🇹🇱'),
  CountryCode(name: 'Turkey', code: 'TR', dialCode: '+90', flag: '🇹🇷'),
  CountryCode(name: 'Turkmenistan', code: 'TM', dialCode: '+993', flag: '🇹🇲'),
  CountryCode(name: 'United Arab Emirates', code: 'AE', dialCode: '+971', flag: '🇦🇪'),
  CountryCode(name: 'Uzbekistan', code: 'UZ', dialCode: '+998', flag: '🇺🇿'),
  CountryCode(name: 'Vietnam', code: 'VN', dialCode: '+84', flag: '🇻🇳'),
  CountryCode(name: 'Yemen', code: 'YE', dialCode: '+967', flag: '🇾🇪'),

  // Pacific/Oceania (Global South)
  CountryCode(name: 'Fiji', code: 'FJ', dialCode: '+679', flag: '🇫🇯'),
  CountryCode(name: 'Kiribati', code: 'KI', dialCode: '+686', flag: '🇰🇮'),
  CountryCode(name: 'Marshall Islands', code: 'MH', dialCode: '+692', flag: '🇲🇭'),
  CountryCode(name: 'Micronesia', code: 'FM', dialCode: '+691', flag: '🇫🇲'),
  CountryCode(name: 'Nauru', code: 'NR', dialCode: '+674', flag: '🇳🇷'),
  CountryCode(name: 'Palau', code: 'PW', dialCode: '+680', flag: '🇵🇼'),
  CountryCode(name: 'Papua New Guinea', code: 'PG', dialCode: '+675', flag: '🇵🇬'),
  CountryCode(name: 'Samoa', code: 'WS', dialCode: '+685', flag: '🇼🇸'),
  CountryCode(name: 'Solomon Islands', code: 'SB', dialCode: '+677', flag: '🇸🇧'),
  CountryCode(name: 'Tonga', code: 'TO', dialCode: '+676', flag: '🇹🇴'),
  CountryCode(name: 'Tuvalu', code: 'TV', dialCode: '+688', flag: '🇹🇻'),
  CountryCode(name: 'Vanuatu', code: 'VU', dialCode: '+678', flag: '🇻🇺'),

  // Original non-Global South entries kept for completeness
  CountryCode(name: 'United States', code: 'US', dialCode: '+1', flag: '🇺🇸'),
  CountryCode(name: 'United Kingdom', code: 'GB', dialCode: '+44', flag: '🇬🇧'),
];